### ISSUE TITLE
Add Social Media Icons

### ISSUE THREAD

**Issue by ali-hall** [jon-athan-hall/tiny-waste#7]
Add links to YouTube, Instagram, Tik Tok and Pinterest

**Comment by Needforname** [comment]
Exactly. I find it odd that very popular icon are not included. There's not even an icon for the dollar sign $. It's a huge inconvenience having to manually create or find and upload matching icons all the time. Especially since the process is quite time consuming. I also wish they offered a set of quality outline style icons. I find many of the included Elementor Font Awesome icons to be quite dated looking. Since icons are a frequently used design element I find it odd Elementor hasn't dedicated more resources to this. I was excited when they announced awhile back that they were adding more icons, but after updating I didn't even notice many additions. I'm wondering if they even updated, as I'm not sure how to tell. Elementor please offer better and more icons.
